# Generated by Django 3.0.3 on 2020-02-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleRelatedSellingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Style')),
            ],
            options={
                'db_table': 'style_related_selling_items',
            },
        ),
        migrations.AddField(
            model_name='style',
            name='style_related_selling_item',
            field=models.ManyToManyField(through='card.StyleRelatedSellingItem', to='product.Product'),
        ),
    ]
