# Generated by Django 3.0.3 on 2020-03-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200229_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='image_url',
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Style')),
            ],
        ),
    ]
