# Generated by Django 3.0.3 on 2020-02-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200229_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-29 03:42:54.992764'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
