# Generated by Django 3.0.3 on 2020-03-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20200302_1138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='styleimage',
            table='style_images',
        ),
    ]
