# Generated by Django 3.0.3 on 2020-03-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20200302_1139'),
        ('card', '0003_auto_20200229_1937'),
    ]

    operations = [
    ]
