# Generated by Django 3.0.3 on 2020-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_merge_20200302_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(default='http://localhost.com', max_length=2000),
            preserve_default=False,
        ),
    ]
