# Generated by Django 3.0.3 on 2020-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=500)),
                ('kakao_id', models.CharField(max_length=100)),
                ('fb_id', models.CharField(max_length=100)),
                ('twt_id', models.CharField(max_length=100)),
                ('gg_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=2)),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
