# Generated by Django 3.0.3 on 2020-02-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='website_url',
            new_name='homepage_url',
        ),
    ]
