# Generated by Django 3.0.3 on 2020-02-29 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followee', to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_relation',
            field=models.ManyToManyField(through='user.Follower', to='user.User'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followee')},
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
    ]
